### ISSUE TITLE
Recurring plans

### ISSUE THREAD

**Issue by CarlQLange** [aldeed/meteor-plans-stripe#5]
Hey,

Great work on these packages, aldeed. Meteor dev wouldn't be the same without you.

I'm curious about recurring plans. If I sign up for a plan, the endDate is a month from then. Is there a flag to set so that the plan will automatically renew on that date?

Related: any chance of an 'upgradePlan' function? For instance, if I have a medium and a high plan, and I'd like to move from medium to high, to have a) the remaining time on the medium plan refunded or b) have the remaining money on the medium plan go towards the high plan cost?

Cheers,
Carl

**Comment by aldeed** [comment]
The `upgradePlan` request is basically what I just wrote up in https://github.com/aldeed/meteor-plans-stripe/issues/6. It's possible but not yet implemented.

Regarding recurring, it should be recurring by default if you set it up as monthly or whatever in Stripe. It should not be setting the `endDate` on the plan unless you cancel it, at which point the `endDate` tells you when the cancelation will be final. Maybe that is a bug.

**Comment by CarlQLange** [comment]
Ah, sorry, I didn't see that. I'll take a look at both issues myself. Cheers!

**Comment by CarlQLange** [comment]
Hey, I'm just checking back in. The `endDate` thing I mentioned was indeed a bug on my side. Thanks a lot for that.

I'm looking into `upgradePlan` and time permitting will implement this myself.
