### ISSUE TITLE
Didn't create Stripe Plan?

### ISSUE THREAD

**Issue by MichaelJCole** [aldeed/meteor-plans-stripe#7]
Hi, 

Trying this out.  I got this error when trying to subscribe to my first plan:

```
AppPlans: There was a problem creating Stripe customer: No such plan: betaStarter [Service subscription error trying to add plan betaStarter for user WKP8qqrxxxxT7sMQT
```

It's from [here](https://github.com/aldeed/meteor-plans-stripe/blob/master/plans-stripe-server.js#L80).  

Looking at the code, I think it's expecting the plan to already be made.   Even though payOptions needs an amount.

On first use, I thought the plan data would be stored in the Meteor code.  Plans could be setup with the [Stripe API](https://stripe.com/docs/api#plans). 

My use case was something like this (I wanted the limits to be stored with the price):

```
AppPlans.plans = {};

// Active Plans

AppPlans.plans.betaFreemium = {
  name: 'Freemium',
  amount: 0,
  limit: 5,
  description: 'Fremium Plan',
  action: 'Try Risk-Free',
};
AppPlans.define('betaFreemium');

AppPlans.plans.betaStarter = {
  name: 'Starter',
  amount: 1500,
  limit: 15,
  description: 'Starter Plan',
};
AppPlans.define('betaStarter', {
  services: [
    {
      name: 'stripe',
      planName: 'betaStarter',
      payOptions: _.pick(AppPlans.plans.betaStarter, 'name','description','amount'),
    }
  ],
});
```

Is the project under active development?

**Comment by aldeed** [comment]
Currently you have to go into Stripe and define the plan yourself first. It may be possible to have the package create it for you. I'd accept a PR if someone figures that out.

This package is used in some production apps so the pieces used by those apps are "active" in that we would fix any issues affecting the apps that use it. No one is actively adding new features, but I can look at PRs and/or work with additional maintainers if anyone is interested.

**Comment by MichaelJCole** [comment]
lol, I set out to automate this, then made them manually.  

There's are good business/opsec reasons to separate the plans from the code. 

Also, I see now that payOptions needs the amount to get the stripe token.  Anyways, all is well :-)
